var car = "Ferrari";
console.log("is car ==`Ferrari`? I predict True.");
console.log(car == "Ferrari");
console.log("is car == Mazda? predict False");
console.log(car == "Mazda");
console.log("is car == Suzuki? predict False");
console.log(car == "Suzuki");
console.log("is car == Honda? predict False");
console.log(car == "Honda");
console.log("is car == BMW? predict False");
console.log(car == "BMW");
console.log("is car == Mazda? predict True");
console.log(car == "Mazda");
console.log("is car == Suzuki? predict True");
console.log(car == "Suzuki");
console.log("is car == Honda? predict True");
console.log(car == "Honda");
console.log("is car == BMW? predict True");
console.log(car == "BMW");
console.log("is car == Ford? predict True");
console.log(car == "Ford");
